MicrosoftDocs/AdaptiveCards

AdaptiveCards/get-started/Bots.md
=> Minor fixes

AdaptiveCards/resources/Tools.md
Add VSCode plugin usage, options info for quick reference.
=> Add VSCode plugin usage, options info

AdaptiveCards/create/libraries/NET.md
TextSizes does not exist. TextSize is right.
=> Fix typo in code, create

AdaptiveCards/display/libraries/HTMLServer.md
API doc matches the API after the refactoring changes I made
=> HTML Server final API doc

AdaptiveCards/create/GettingStarted.md
=> Fixed a minor typo

AdaptiveCards/display/ImplementingRenderer.md
This one is correct - please ignore my previous edit. MD editor in GitHub not so much... ;P
=> Fixing my fix... fumbled a little.

AdaptiveCards/docfx.json
Note that the LiveFyre commenting system is no longer being supported by the docs platform. In place, they have built this feedback tool that integrates with GitHub issues on your repo. You will be able to view, respond, assign, or close issues in the issues tab of the repo.
=> Update feedback tool

AdaptiveCards/authoring-cards/card-schema.md, AdaptiveCards/rendering-cards/host-config.md
In preparation for Adaptive Cards 1.1, update schema docs for cards and HostConfig.
=> Update docs for 1.1 release

AdaptiveCards/sdk/rendering-cards/net-html/render-a-card.md
Changed to IList<AdaptiveWarning> warnings = renderedCard.Warnings;
=> Spelling fix

AdaptiveCards/sdk/rendering-cards/android/extensibility.md
Add extensibility changes for image loading, media loading and an empty section for action loading to be completed when the full version of v1.2 is released
=> Add extensibility changes for all versions

AdaptiveCards/sdk/rendering-cards/net-wpf/actions.md
Update the type from to ActionEventArgs to AdaptiveActionEventArgs
=> Fix type of Action args

AdaptiveCards/sdk/rendering-cards/android/getting-started.md
Adds the information needed to find the maven packages and to import the adaptivecards object model and renderer
=> Add installation and import information

AdaptiveCards/sdk/rendering-cards/android/native-styling.md
Add instructions on how to style actions based on sentiments and inline actions, both properties added in v1.2 of AdaptiveCards
=> Add styling added for v1.2

AdaptiveCards/sdk/rendering-cards/android/actions.md
Add the breaking change from version 1.1 which include the onMediaPlay and onMediaStop actions
=> Add actions breaking change from v1.1

AdaptiveCards/sdk/rendering-cards/android/render-a-card.md
Adds the breaking changes included in v1.2 of adaptive cards, also fixed the original way of rendering the card
=> Add information on card rendering for android

AdaptiveCards/sdk/rendering-cards/android/extensibility.md
Updates custom action rendering and custom element rendering sections
=> [Android] Update extensibility

AdaptiveCards/sdk/rendering-cards/android/actions.md
Changes the location of "Breaking changes for v1.1" to the bottom while adding a link to the top to make it more visible
=> [Android] Update Actions

AdaptiveCards/sdk/rendering-cards/android/render-a-card.md
Updates the description of the ParseContext contents and fixes samples
=> [Android] Update Render a Card

AdaptiveCards/sdk/rendering-cards/ios/host-config.md, AdaptiveCards/sdk/rendering-cards/ios/native-styling.md
updated native styling for iOS
=> iOS native style doc update

AdaptiveCards/templating/sdk.md
Contributor has reported possible source content issue. 
Affected Line: 69
Description: "instamce" should be "instance"
=> CC191749 - Fixing Typo

AdaptiveCards/authoring-cards/getting-started.md, AdaptiveCards/authoring-cards/text-features.md, AdaptiveCards/getting-started/bots.md, AdaptiveCards/getting-started/windows.md, AdaptiveCards/resources/tools.md, AdaptiveCards/sdk/rendering-cards/net-wpf/native-styling.md, AdaptiveCards/sdk/rendering-cards/uwp/native-styling.md, ThirdPartyNotices
DEV TASK 248889. Change http to https.
scan and replace http with https by using regex as below,
```
(\]\(|href=")http://([a-zA-Z\.]*(microsoft.com|office.com))
(\]\(|href=")http://([a-zA-Z\.]*(msdn.com|aka.ms))
(\]\(|href=")http://([a-zA-Z\.]*(github.com|powerbi.com))
(\]\(|href=")http://([a-zA-Z\.]*(powerapps.com|adaptivecards.io))
(\]\(|href=")http://([a-zA-Z\.]*(skype.com|dynamics.com))
(\]\(|href=")http://([a-zA-Z\.]*(contoso.com|fourthcoffee.com))
(\]\(|href=")http://([a-zA-Z\.]*(windowsservercatalog.com|iis.net))
$1https://$2
http?://(([a-zA-Z0-9]+[.])*(microsoft.com|office.com))
http?://(([a-zA-Z0-9]+[.])*(msdn.com|aka.ms))
http?://(([a-zA-Z0-9]+[.])*(github.com|powerbi.com)) 
http?://(([a-zA-Z0-9]+[.])*(powerapps.com|adaptivecards.io)) …
```
=> change http to https

AdaptiveCards/sdk/rendering-cards/android/native-styling.md
Indicate that limited native styling available for Action.ShowCard on android
=> [Android] Action.ShowCard native styling

AdaptiveCards/sdk/rendering-cards/javascript/extensibility.md
=> Update JS extensibility doc to include 2.0 model

AdaptiveCards/authoring-cards/input-validation.md, AdaptiveCards/toc.yml
=> Cherry-pick to 'live': Add documentation for input validation #315

AdaptiveCards/resources/future.md
Fixes https://github.com/microsoft/AdaptiveCards/issues/4901
- Updated roadmap link
- Updated link to "Submit ideas"
=> Update future.md with links to productboard

AdaptiveCards/sdk/rendering-cards/javascript/extensibility.md
This PR adds details on how to implement custom inputs with the JS SDK.
=> Update JS extensibility page for inputs

AdaptiveCards/resources/partners.md
Web Chat version 4.10.0 was released today. This updates `partners.md` to match.
=> Update Web Chat version

AdaptiveCards/sdk/rendering-cards/javascript/render-a-card.md
- instead of the deprecated processMarkdown
=> Javascript > Update example to use onProcessMarkdown

AdaptiveCards/resources/partners.md
Removed an empty line which caused the table markdown for Live providers to render improperly.
=> Remove whitespace to fix table formatting

AdaptiveCards/sdk/rendering-cards/net-html/getting-started.md
Due to resource constraints we don't have capacity to support the .NET HTML package. This decision is still underway so please let us know if you heavily depend on this and/or would like to contribute to keep it going
=> Tentative update to the .NET HTML project to mark maintenance mode

AdaptiveCards/authoring-cards/universal-action-model.md
=> Links: Adaptive Cards (2021-02)

AdaptiveCards/resources/partners.md
=> Update Web Chat to 4.12.0 with Adaptive Cards 2.5.0

AdaptiveCards/sdk/rendering-cards/ios/extensibility.md
* Resource resolver & additional properties are updated
* Updated per review comments
=> [iOS] Resource resolver & additional properties are updated

AdaptiveCards/sdk/rendering-cards/ios/extensibility.md
* Update extensibility.md
Updated it with Resource Resolver and swift example for additional properties.
* Update extensibility.md
* Update extensibility.md
* Update extensibility.md
=> Update extensibility.md (#363)

AdaptiveCards/resources/partners.md
=> Update partners.md with Web Chat patch

AdaptiveCards/sdk/rendering-cards/react-native/theme-config.md
=> [ React_Native SDK ] Updated new properties in the theme config

AdaptiveCards/resources/partners.md
FYI, in this release, we did not bump AC because our dev cycle for this release was rather short. We will bump again in the next release.
=> Updating Web Chat to 4.13.0

AdaptiveCards/templating/service.md
"Templatng" corrected to "templating".
=> Small typo fix

AdaptiveCards/sdk/rendering-cards/react-native/getting-started.md
=> Updated Maintainer Info

AdaptiveCards/getting-started/windows.md, AdaptiveCards/resources/media.md
=> Old channle9 video link removed

AdaptiveCards/sdk/rendering-cards/react-native/getting-started.md
Fix broken link to AC repository
--
CC: @matthidinger
=> Fix broken link

AdaptiveCards/authoring-cards/getting-started.md
**Global effort to fix broken links**
@matthidinger
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
=> [BrokenLinksH2] fixing broken links

AdaptiveCards/sdk/rendering-cards/net-html/getting-started.md
**Global effort to fix broken links**
@matthidinger
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
=> [BrokenLinksH2] fixing broken link

AdaptiveCards/sdk/rendering-cards/xamarin/android/getting-started.md
removing broken link, file no longer exists.
**Global effort to fix broken links**
@almedina-ms 
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
=> [BrokenLinksH2] removing broken link

AdaptiveCards/getting-started/outlook.md
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute
**Global effort to fix build validation errors**
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only build validation fixes and does not change other content.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05 …
=> [BULK UPDATES] DocuTune - Fix build validation issues: docs-link-absolute

AdaptiveCards/getting-started/windows.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
**DO NOT MERGE THIS PULL REQUEST WHILE IN DRAFT STATUS!** Some of the changes to links and other content are not valid until after go-live.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: …
=> [BULK UPDATE] DocuTune - Rebranding links

AdaptiveCards/resources/partners.md
=> Update Web Chat to 4.15.6 with AC 2.11.1

AdaptiveCards/sdk/rendering-cards/winui-3/actions.md, AdaptiveCards/sdk/rendering-cards/winui-3/extensibility.md, AdaptiveCards/sdk/rendering-cards/winui-3/getting-started.md, AdaptiveCards/sdk/rendering-cards/winui-3/host-config.md, AdaptiveCards/sdk/rendering-cards/winui-3/native-styling.md, AdaptiveCards/sdk/rendering-cards/winui-3/render-a-card.md
Added WinUI 3 renderer documentation. NOTE: Links to NuGet will be invalid until the release is out.
=> Added documentation for WinUI 3 renderer

AdaptiveCards/resources/partners.md
=> Update Web Chat 4.15.8

AdaptiveCards/rendering-cards/renderer-behaviour.md
@almedina-ms
The C&E Skilling team is fixing build validation errors on Learn.microsoft.com. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content.
Please kindly review and merge, or provide feedback within 3 business days. After that time, we have approval to self-merge and publish these changes If you have any questions or feedback on this effort, please contact [Ryan Thompson](mailto:ryanth@microsoft.com)
=> Global effort to fix validation errors

AdaptiveCards/index.md, AdaptiveCards/resources/media.md
Move our video links to use our new CDN.
=> Move to cdn.adaptivecards.io
